### ISSUE TITLE
i  need   Content-Length    from  stream()

### ISSUE THREAD

**Issue by wenfer** [calne-ca/subsonic-java-client#7]
subsonic api  
https://www.subsonic.org/pages/api.jsp#stream

if set estimateContentLength  is true  

the Content-Length HTTP header will be set to an estimated value for transcoded or downsampled media.

**Comment by calne-ca** [comment]
I've just released a new version 0.6.0 for this.

See release notes for details:
https://github.com/calne-ca/subsonic-java-client/releases/tag/0.6.0

Feel free to create a new issue when you face any issues,

**Comment by wenfer** [comment]
i  tried  set SubsonicPreferences.estimateContentLength is true

but  content-length   always  null

**Comment by calne-ca** [comment]
My implementation was a little bit unclean, the getContentLength method only returns the content length if the input stream has been created before, otherwise it will just return null. This only happens when you explicitly call the getInputStream method before. I'll fix this in 0.6.1 later but for now it should be enough to simply call the getInputStream method before you call the getContentLength method. I tested it with two embedded servers and my own airsonic server and it worked in all cases.

Tell me if that workaround worked for you or if you face any other issues.
As mentioned, I'll provide a proper fix later.

**Comment by wenfer** [comment]
that  was  released ?   look like you are forgot it

**Comment by calne-ca** [comment]
No, I didn't release 0.6.1 yet. I didn't have the time yet and also wanted to wait for your response to see if there is anything else that needs fixing that I could include in 0.6.1. That's why I explained how you can get it to work with 0.6.0 (with a workaround) so you can try that until I released 0.6.1

**Comment by wenfer** [comment]
you are  right  ,   call  getContentLength  after  getInputStream   , it's worked  

that's don't need 0.6.1

my case   fixed     ,  if  i got any  problem , i will create other  issues

**Comment by wenfer** [comment]
sorry , i  don't know if it's a problem ,  getContentLength not  equals   the  downloaded  file length

**Comment by calne-ca** [comment]
You mean the file downloaded with the download() method?
The download() method gives you the files as saved on the server so the length might differ from whatever you get from the stream() method since the stream API gives you transcoded and possibly down sampled audio streams depending on your configured max bit rate and audio format.

If you mean that the the size of all bytes in the input stream differs from what it states in the content length, that's also possible:
I did some tests against subsonic and airsonic and the behaviour is kinda inconsistent.
Seems like the estimateContentLength param is kinda unreliable.

With subsonic, when setting estimateContentLength to false the behaviour is consistent. The content length will match the actual stream length and the length always stays the same for the same song. When setting estimateContentLength to true streaming the exact same song multiple times with the same bitrate can result in byte streams of different size. The content length always stays the same though so it might differ from the actual stream length. What's also super weird is that, with subsonic, the value of estimateContentLength doesn't only effect the content length it actually has an effect on the resulting stream. When set to true the streams are always way smaller than without it. So it seems like the parameter also controls whether or not it down samples the audio to your configured max bit rate.

Airsonic on the other hand seems to completely ignore the estimateContentLength param. So regardless of what value you set it to, the content length always matches the download size and the download size is always the same even across multiple streams of the same song. It also always down samples the audio to your max bit rate. So airsonic is consistent and predictable but it simply doesn't seem to support the estimateContentLength  parameter and instead just implemented that behaviour by default.

So not really an issue with the client just weird API behaviour.
